CarpetX: Move unused variables inside CCTK_DEBUG
EinsteinToolkit/CarpetX pull request #292
Opened 2024-06-24 16:30 UTC by lwJi

2024-10-31 19:54 UTC, rhaas80 approved these changes

2024-11-01 19:07 UTC, rhaas80 commented
Needs to fix conflicts before it can be merged in.

2024-11-01 19:35 UTC, lwJi commented
> Needs to fix conflicts before it can be merged in.

Done. But I think the CI is broken for the moment

2024-11-01 20:28 UTC, eschnett commented
I'm very close to merging the CI fix.

2024-11-02 04:02 UTC, lwJi commented
> I'm very close to merging the CI fix.

Thanks, @eschnett

2024-11-02 20:41 UTC, eschnett commented on CarpetX/src/prolongate_3d_rf2_impl.hxx
> +#ifdef CCTK_DEBUG
Same here.

2024-11-02 20:42 UTC, eschnett requested changes
I would prefer a `CCTK_ATTRIBUTE_MAYBE_UNUSED` instead.

2024-11-11 16:31 UTC, closed without merging